title: react-native-ble-manager
email: info@innove.it
description: >-
  react-native-ble-manager documentation
baseurl: "/react-native-ble-manager"
url: "https://innoveit.github.io"

theme: just-the-docs

aux_links:
  "Project on GitHub":
    - "//github.com/innoveit/react-native-ble-manager"